### ISSUE TITLE
The JSON File for current version of GHE Server is not working

### ISSUE THREAD

**Issue by bamboomaster112** [jwiebalk/docker-elgk#4]
The data is not available in Grafana Server when we create dashboard in Grafana using JSON Export in GHE Server Appliance 2.20,5
and Grafana Server version is 7.2.0

**Comment by jwiebalk** [comment]
Grafana usually has breaking changes between major versions that effect exporting and importing dashboards. the "build-in" grafana on a GHES instance is currently 4.6.3.

You can try the grafana5 dashboard I have at https://github.com/jwiebalk/github-enterprise-grafana-dashboard/tree/master/Grafana5 and see if that works.

**Comment by bamboomaster112** [comment]
Yes, I checked with Grafana5 JSON File
It seems to be working !
Thanks
