### ISSUE TITLE
Setting Up Stack for GitHub External Monitoring

### ISSUE THREAD

**Issue by bamboomaster112** [jwiebalk/docker-elgk#5]
- [ ] Not Working
- I tried the docker compose YAML File only using Collectd, Grafana, and Graphite and removed ElasticSearch, Kibana, Logstash - It was not working
- [x] Working
- Wheh I tried with docker compose YAML File only using Collectd, Grafana, Graphite and ElasticSearch, and removed Kibana, Logstash - It was working

**Comment by bamboomaster112** [comment]
@jwiebalk What may be causing this problem, I see that Grafana used ElasticSearch, do we need ElasticSearch to run Grafana..

**Comment by jwiebalk** [comment]
Elasticsearch is only needed if you want to collect the syslog entries from the GHES instance. That'll go into Logstash which will write those to elasticsearch. You'd then be able to add that as a source in Grafana to see those log files.

**Comment by bamboomaster112** [comment]
So If I remove Logstash and Kibana, is there any effect on statistics collected from collectd server which is then written to graphite, which is then used in grafana

**Comment by PramodhKumarM** [comment]
Hi @jwiebalk :wave:

May I know why Logstash and Kibana are used in this stack

**Comment by bamboomaster112** [comment]
Hi @jwiebalk 👋 

May I know why Logstash and Kibana are used in Stack
If I enable log forwarding in GHE Server, can I receive logs into Logstash 🤔
